name: Jira Integration
description: Github to Jira Integration Action
author: 'drew.mercer@brandlive.com'
inputs:
  action:
    description: 'Action to perform'
    required: true
  token: 
    description: 'Jira API token in the form of user_email:api_token'
    required: true
  jira_url:
    description: 'Jira URL of your instance'
    required: true
  project:
    description: 'Jira project key'
    required: true
  issue_type:
    description: 'Jira issue type'
    required: false
  summary:
    description: 'Jira issue summary'
    required: false
  description:
    description: 'Jira issue description'
    required: false
  priority:
    description: 'Jira issue priority'
    required: false

runs:
  using: "composite"
  steps:
  - id: create
    if: ${{ inputs.action == 'create' }}
    run: |
      issuetype_id="${{ inputs.issue_type }}"
      project_id="${{ inputs.project }}"
      priority_id="${{ inputs.priority }}"
      description="${{ inputs.description }}"
      summary="${{ inputs.summary }}"
      template='{

        "fields": {
          "summary": "%s",
          "issuetype": {
            "id": "%s"
          },
          "project": {
            "id": "%s"
          },
          "priority": {
            "id": "%s"
          },
          
          "description": {
            "type": "doc",
            "version": 1,
            "content": [
              {
                "type": "paragraph",
                "content": [
                  {
                    "text": "%s",
                    "type": "text"
                  }
                ]
              }
            ]
          }
        }
      }'

      payload=$(printf "$template" \
              "$summary" \
              "$issuetype_id" \
              "$project_id" \
              "$priority_id" \
              "$description")
      auth="echo -n ${{ inputs.jira_token }} | base64"
      curl -i -X POST \
          -H "Authorization: Basic $auth" \ \
          -H "Content-Type:application/json" \
          -H "X-Atlassian-Token:no-check" \
          "${{ inputs.jira_url }}" \
          -d \
          "$payload"
    shell: bash              